//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace leBlog.MarkupParser.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("leBlog.MarkupParser.Config.ConfigResources", typeof(ConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;transformers&gt;
        ///  &lt;transformer markupStart=&quot;#!&quot; markupEnd=&quot;!#&quot; cssClass=&quot;lb-header&quot; /&gt;
        ///  &lt;transformer markupStart=&quot;#*&quot; markupEnd=&quot;*#&quot; cssClass=&quot;lb-bold&quot; /&gt;
        ///  &lt;transformer markupStart=&quot;#/&quot; markupEnd=&quot;/#&quot; cssClass=&quot;lb-italic&quot; /&gt;
        ///  &lt;transformer markupStart=&quot;#_&quot; markupEnd=&quot;_#&quot; cssClass=&quot;lb-underlined&quot; /&gt;
        ///  &lt;imgTransformer markupStart=&quot;#I&quot; markupEnd=&quot;I#&quot; cssClass=&quot;lb-image&quot; /&gt;
        ///&lt;/transformers&gt;.
        /// </summary>
        internal static string Transformers {
            get {
                return ResourceManager.GetString("Transformers", resourceCulture);
            }
        }
    }
}
